//Walks data
export const walks = [
  {
    walkId: 1,
    photoPath: "walk1.jpg",
    walkName: "Middleton-Top",
    location: "Wirksworth, Matlock",
    lat: 53.092788,
    lng: -1.586342,
    walkType: ["Hilly"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: true,
    waterOnRoute: false,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 2,
    photoPath: "walk2.jpg",
    walkName: "Stoney-Wood",
    location: "Wirksworth, Matlock",
    lat: 53.085789,
    lng: -1.575819,
    walkType: ["Hilly", "Woods"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: false,
    waterOnRoute: false,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 3,
    photoPath: "walk3.jpg",
    walkName: "Crich Tramway Village",
    location: "Matlock",
    lat: 53.090478,
    lng: -1.48667,
    walkType: ["Hilly", "Flat", "Park"],
    offLeadAreas: false,
    paths: true,
    animalsOnRoute: false,
    toilets: true,
    waterOnRoute: false,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 4,
    photoPath: "walk4.jpg",
    walkName: "Shining Cliff Woods",
    location: "Alderwasley, Belper",
    lat: 53.080292,
    lng: -1.508166,
    walkType: ["Hilly", "Forest"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: false,
    waterOnRoute: false,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 5,
    photoPath: "walk5.jpg",
    walkName: "Nine Ladies Stanton Moor",
    location: "Birchover, Matlock",
    lat: 53.168099,
    lng: -1.628827,
    walkType: ["Hilly", "Flat"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: false,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 6,
    photoPath: "walk6.jpg",
    walkName: "Stanton Stroll",
    location: "Matlock, Stanton in Peak",
    lat: 53.16905,
    lng: -1.633165,
    walkType: ["Hilly", "Forest"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: false,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 7,
    photoPath: "walk7.jpg",
    walkName: "Codnor Castle",
    location: "Nottingham",
    lat: 53.04389,
    lng: -1.363996,
    walkType: ["Flat", "Woods"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: false,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 8,
    photoPath: "walk8.jpg",
    walkName: "Elvaston Castle",
    location: "Elvaston, Derby",
    lat: 52.892928,
    lng: -1.395229,
    walkType: ["Flat", "Park"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: true,
    waterOnRoute: true,
    scenic: false,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 9,
    photoPath: "walk9.jpg",
    walkName: "Portland Park",
    location: "Kirkby in Ashfield, Nottingham",
    lat: 53.104783,
    lng: -1.255821,
    walkType: ["Hilly", "Flat", "Forest", "Park"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: false,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 10,
    photoPath: "walk10.jpg",
    walkName: "Ticknall Limeyards Loop",
    location: "Ticknall, Derby",
    lat: 52.811978,
    lng: -1.4666,
    walkType: ["Forest"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 11,
    photoPath: "walk11.jpg",
    walkName: "Langshaw Estate",
    location: "Longshaw Estate, Sheffield",
    lat: 53.309941,
    lng: -1.613916,
    walkType: ["Forest", "Flat", "Fields"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 12,
    photoPath: "walk12.jpg",
    walkName: "Dale Abbey Loop",
    location: "Ilkeston",
    lat: 52.948523,
    lng: -1.350173,
    walkType: ["Hilly", "Forest"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: false,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 13,
    photoPath: "walk13.jpg",
    walkName: "Linacre Reservoirs",
    location: "Chesterfield",
    lat: 53.250362,
    lng: -1.497585,
    walkType: ["Flat", "Forest"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 14,
    photoPath: "walk14.jpg",
    walkName: "Hardwick Hall",
    location: "Chesterfield",
    lat: 53.168926,
    lng: -1.308694,
    walkType: ["Flat", "Park"],
    offLeadAreas: false,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: false,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 15,
    photoPath: "walk15.jpg",
    walkName: "Calke Abbey",
    location: "Derby",
    lat: 52.799869,
    lng: -1.455841,
    walkType: ["Hilly", "Flat", "Forest", "Park"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 16,
    photoPath: "walk16.jpg",
    walkName: "Shipley Country Park",
    location: "Heanor",
    lat: 52.993715,
    lng: -1.345075,
    walkType: ["Park"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 17,
    photoPath: "walk17.jpg",
    walkName: "Mam Tor",
    location: "Hope Valley, Derbyshire",
    lat: 53.349609,
    lng: -1.80989,
    walkType: ["Hilly"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 18,
    photoPath: "walk18.jpg",
    walkName: "Milton to Foremark Loop",
    location: "Milton, Derby",
    lat: 52.814022,
    lng: -1.503218,
    walkType: ["Hilly", "Forest", "Beach"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 19,
    photoPath: "walk19.jpg",
    walkName: "Monsal Dale",
    location: "Peak District, Derbyshire",
    lat: 53.242074,
    lng: -1.72758,
    walkType: ["Hilly"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: true,
    waterOnRoute: false,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 20,
    photoPath: "walk20.jpg",
    walkName: "Chatsworth Estate",
    location: "Peak District, Derbyshire",
    lat: 53.5074,
    lng: -1.63783,
    walkType: ["Hilly", "Flat"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: true,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 21,
    photoPath: "walk21.jpg",
    walkName: "The Robin Hood Inn Pub Walk",
    location: "Peak District, Derbyshire",
    lat: 53.349531,
    lng: -1.49755,
    walkType: ["Hilly"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 22,
    photoPath: "walk22.jpg",
    walkName: "Stanage Edge",
    location: "Peak District, Derbyshire",
    lat: 53.347983,
    lng: -1.632888,
    walkType: ["Hilly"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: true,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 23,
    photoPath: "walk23.jpg",
    walkName: "Curbar Edge",
    location: "Peak District, Derbyshire",
    lat: 53.270383,
    lng: -1.611735,
    walkType: ["Moors", "Hilly"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: true,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 24,
    photoPath: "walk24.jpg",
    walkName: "Jacob's Ladder",
    location: "Peak District, Derbyshire",
    lat: 53.374562,
    lng: -1.870815,
    walkType: ["Moors", "Hilly"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: false,
    waterOnRoute: true,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 25,
    photoPath: "walk25.jpg",
    walkName: "Padley Gorge",
    location: "Peak District, Derbyshire",
    lat: 53.307801,
    lng: -1.623938,
    walkType: ["Woodland", "Hilly", "Flat"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 26,
    photoPath: "walk26.jpg",
    walkName: "Cresswell Crags",
    location: "Worksop, Derbyshire",
    lat: 53.26369,
    lng: -1.19354,
    walkType: ["Forest", "Flat"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 27,
    photoPath: "walk27.jpg",
    walkName: "Longdendale Trail",
    location: "Glossop, Derbyshire",
    lat: 53.462208,
    lng: -1.963632,
    walkType: ["Flat"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 28,
    photoPath: "walk28.jpg",
    walkName: "Kedleston Hall",
    location: "Derby, Derbyshire",
    lat: 52.959851,
    lng: -1.53906,
    walkType: ["Hilly", "Flat", "Forest", "Park"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: true,
    toilets: true,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
  {
    walkId: 29,
    photoPath: "walk29.jpg",
    walkName: "Monsal Trail",
    location: "Buxton",
    lat: 53.242292,
    lng: -1.730401,
    walkType: ["Flat"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: true,
    waterOnRoute: false,
    scenic: false,
    parking: "paid",
    approved: true,
  },
  {
    walkId: 30,
    photoPath: "walk30.jpg",
    walkName: "Grassmoor Country Park",
    location: "Chesterfield, Derbyshire",
    lat: 53.23812,
    lng: -1.425693,
    walkType: ["Flat"],
    offLeadAreas: true,
    paths: true,
    animalsOnRoute: false,
    toilets: false,
    waterOnRoute: true,
    scenic: true,
    parking: "free",
    approved: true,
  },
];
